addons:
  apt:
    packages:
    - libgmp-dev
language: c
sudo: required
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
os:
- linux
- osx
before_install:
- bash tools/install-stack.sh
- bash tools/install-ghr.sh
script:
- stack setup
- stack build --ghc-options -O2 --pedantic
- bash tools/attach-binary.sh
